declare module '@eslint/js';
declare module 'eslint-plugin-i';
declare module 'eslint-plugin-eslint-comments';
declare module 'eslint-plugin-simple-import-sort';
declare module 'eslint-plugin-react';
declare module 'eslint-plugin-react-hooks';
declare module 'eslint-plugin-react-refresh';
declare module 'eslint-plugin-vue';
declare module 'eslint-plugin-markdown';
